<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="ej.finsys.modules.Login" tests="9" time="164.285" ignored="18" failures="2" timestamp="19 Aug 2018 15:02:18 GMT" skipped="0" hostname="DESKTOP-IUV45J7" errors="0">
  <testcase name="ExecuteLogin" time="20.485" classname="ej.finsys.modules.Login">
    <failure type="java.lang.AssertionError" message="expected [Welcome dummy[CFO]] but found [Welcome dummy[RM]]">
      <![CDATA[java.lang.AssertionError: expected [Welcome dummy[CFO]] but found [Welcome dummy[RM]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at ej.finsys.modules.Login.ExecuteLogin(Login.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin2" time="15.371" classname="ej.finsys.modules.Login"/>
  <testcase name="Executeloginwithinvalid" time="20.402" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin2" time="15.369" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin2" time="15.386" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin" time="20.482" classname="ej.finsys.modules.Login">
    <failure type="java.lang.AssertionError" message="expected [Welcome dummy[CFO]] but found [Welcome dummy[FM]]">
      <![CDATA[java.lang.AssertionError: expected [Welcome dummy[CFO]] but found [Welcome dummy[FM]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at ej.finsys.modules.Login.ExecuteLogin(Login.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" time="25.983" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin2" time="15.409" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin2" time="15.398" classname="ej.finsys.modules.Login"/>
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="ExecuteLogin" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="Executeloginwithinvalid" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- Executeloginwithinvalid -->
  <testcase name="ExecuteLogin2" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin2 -->
  <testcase name="ExecuteLogin2" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin2 -->
  <testcase name="ExecuteLogin2" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin2 -->
  <testcase name="ExecuteLogin2" classname="ej.finsys.modules.Login">
    <skipped/>
  </testcase> <!-- ExecuteLogin2 -->
</testsuite> <!-- ej.finsys.modules.Login -->
